[workspace]
resolver = "2"
members = [
    "crates/markraft-doc",
    "crates/markraft-markdown",
    "crates/markraft-gpui",
    "crates/markraft-vim",
    "crates/markraft-app",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"
repository = "https://github.com/ahonn/markraft"

[workspace.dependencies]
gpui = { package = "gpui-pre", version = "=0.3.4" }
gpui_platform = { package = "gpui-pre-platform", version = "=0.3.4", features = ["font-kit", "runtime_shaders"] }
markraft-doc = { path = "crates/markraft-doc" }
markraft-markdown = { path = "crates/markraft-markdown" }
markraft-gpui = { path = "crates/markraft-gpui" }
markraft-vim = { path = "crates/markraft-vim" }

[profile.dev]
debug = 1

[profile.dev.package."*"]
debug = 0
